version: '3'

services:
  flask:
    build: .
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - postgres
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=development

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile.celery
    volumes:
      - .:/app
    depends_on:
      - redis
      - postgres

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile.celery
    command: celery -A tasks beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - postgres

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
